databases:
  - name: workout_DB
    databaseName: workout_db_07ch
    user: workout
    region: singapore

services:
  - type: web
    name: workout
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: workout_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

